name: Continuous delivery

on: 
  workflow_dispatch: 

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get docker version
        run: docker -v
      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        