name: Continuous delivery

on: 
  workflow_dispatch: 

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get docker version
        run: docker -v
      - name: Build Docker images
        working-directory: ./hangman-api
        run: docker build -t vicentett1/hangman-api-cep:latest .
        