name: Integracion continua

on:
  push:
    branches: [ main ]
    paths: [ "hangman-api/**" ]
  pull_request: 
    branches: [ main ]
    paths: [ "hangman-api/**" ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 17, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up node.js version
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version}}
      - name: Build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build
          npm run test