name: Integracion continua

on:
  push:
    branches: [ main ]
    paths: [ "hangman-api/**" ]
  pull_request: 
    branches: [ main ]
    paths: [ "hangman-api/**" ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build
          npm run test