name: Integracion continua

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: inspect machine
        run: |
          ls -al
          whoami
          pwd
          node -v